version: '3'
services:

  #PHP Service
  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: moodle
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: moodle
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - moodledata:/var/moodledata
    networks:
      - moodle-network

  #Nginx Service
  moodle_webserver:
    image: nginx:alpine
    container_name: moodle_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8071:80"
      - "44371:443"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - moodle-network

  #Mysql database
  moodledb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - moodle_dbdata:/var/lib/mysql
    networks:
      - moodle-network
    ports:
      - 33679:3306

volumes:
  moodle_dbdata:
  moodledata:

#Networks
networks:
  moodle-network:
    driver: bridge
